"""State definition for Legal and Regulatory Agent subgraph."""

from typing import Any

from pydantic import BaseModel, Field


class LegalState(BaseModel):
    """State passing through the Legal and Compliance LangGraph subgraph."""

    tenant_id: str
    venture_id: str
    jurisdiction: str
    query: str
    retrieved_chunks: list[dict[str, Any]] = Field(default_factory=list)
    citation_refs: list[str] = Field(default_factory=list)
    decision: str = "abstain"  # answer, abstain, clarify
    analysis: str = ""
    disclaimer: str = (
        "Disclaimer: This informational statutory analysis is generated by Cofunder AI "
        "and does not constitute licensed legal advice or an attorney-client relationship."
    )
    requires_human_counsel: bool = False
    summary: str = ""
